### ISSUE TITLE
Integrated compilation system.

### ISSUE THREAD

**Issue by ghost** [SynneK1337/schoolMiner#1]
Przewrotny, can you add makefile or so to compile py file into executables?
Also with release you could compile it to .pyc files via this:
```bash
python -m py_compile fileA.py fileB.py fileC.py ...
```

I suggest using pypy for real native speed of your schoolMiner:
https://pypy.org/

~Szczep

**Comment by obrotowy** [comment]
Soon

**Comment by SynneK1337** [comment]
:soon:

**Comment by obrotowy** [comment]
Nie umiesz w issue

**Comment by obrotowy** [comment]
Look at release tab :)
